language: python
python:
  - "2.7"
services:
  - docker
script:
  - docker login -u${DOCKER_USER} -p${DOCKER_USER_PASSWORD}
  - pip install jinja2 -y
  - python sync.py
branches:
  only:
    - sync
notifications:
  email:
    - me@xiexianbin.cn
